import type { AudioAsset, ComponentStatus, SongProject, StudioJob, VoiceProfile } from "./types";

// Deterministic tiny pseudo-random for waveform peaks
function peaks(seed: number, count = 96): number[] {
  const out: number[] = [];
  let s = seed;
  for (let i = 0; i < count; i++) {
    s = (s * 9301 + 49297) % 233280;
    const base = 0.35 + (s / 233280) * 0.55;
    const env = 0.5 + 0.5 * Math.sin((i / count) * Math.PI * 2 + seed);
    out.push(Math.max(0.05, Math.min(1, base * env)));
  }
  return out;
}

const now = new Date("2026-07-18T14:20:00Z").toISOString();
const iso = (offsetMinutes: number) =>
  new Date(Date.parse(now) - offsetMinutes * 60_000).toISOString();

export const SEED_SONGS: SongProject[] = [
  {
    id: "song_iron-halcyon",
    title: "Iron Halcyon",
    slug: "iron-halcyon",
    stage: "mixing",
    bpm: 148,
    key: "E minor",
    timeSignature: "4/4",
    genreTags: ["metalcore", "electronic"],
    moodTags: ["driving", "cinematic"],
    creativeBrief:
      "Cinematic metalcore opener. Verse pushes tight muted riffs against sparse synth pads, chorus opens to a wall of layered guitars and half-time drums.",
    structureTemplate: "Intro / Verse / Chorus / Verse / Chorus / Breakdown / Final Chorus / Outro",
    targetDurationSeconds: 220,
    folderPath: "D:\\Varynt\\Projects\\iron-halcyon",
    createdAt: iso(60 * 24 * 9),
    updatedAt: iso(38),
    counts: { generations: 8, stems: 4, vocals: 2, mixes: 2, masters: 0 },
  },
  {
    id: "song_ashline-drift",
    title: "Ashline Drift",
    slug: "ashline-drift",
    stage: "selecting",
    bpm: 92,
    key: "F# minor",
    timeSignature: "4/4",
    genreTags: ["hip-hop", "alt-metal"],
    moodTags: ["hazy", "heavy"],
    creativeBrief:
      "Slow trap-adjacent hip-hop bed with distorted guitar accents. Aiming for a hazy, half-time verse and a melodic hook.",
    structureTemplate:
      "Intro / Verse / Pre-Chorus / Chorus / Verse / Pre-Chorus / Chorus / Bridge / Final Chorus",
    targetDurationSeconds: 180,
    folderPath: "D:\\Varynt\\Projects\\ashline-drift",
    createdAt: iso(60 * 24 * 3),
    updatedAt: iso(120),
    counts: { generations: 5, stems: 0, vocals: 0, mixes: 0, masters: 0 },
  },
  {
    id: "song_null-vector",
    title: "Null Vector",
    slug: "null-vector",
    stage: "brief",
    timeSignature: "4/4",
    genreTags: ["electronic", "industrial"],
    moodTags: ["cold", "propulsive"],
    creativeBrief:
      "Industrial electronic sketch. No BPM locked yet. Exploring cold synth arps and modular percussion textures.",
    folderPath: "D:\\Varynt\\Projects\\null-vector",
    createdAt: iso(60 * 18),
    updatedAt: iso(60 * 18),
    counts: { generations: 0, stems: 0, vocals: 0, mixes: 0, masters: 0 },
  },
];

export const SEED_ASSETS: AudioAsset[] = [
  {
    id: "asset_gen_ih_1",
    songId: "song_iron-halcyon",
    name: "chorus-wall-v3.wav",
    kind: "generation",
    filePath: "D:\\Varynt\\Projects\\iron-halcyon\\generations\\chorus-wall-v3.wav",
    durationSeconds: 22,
    sampleRate: 44100,
    channels: 2,
    engine: "musicgen",
    model: "small",
    prompt: "electronic metalcore chorus, wall of guitars, half-time drums, wide synths",
    seed: 8412,
    favorite: true,
    createdAt: iso(60 * 5),
    waveformPeaks: peaks(1),
  },
  {
    id: "asset_gen_ih_2",
    songId: "song_iron-halcyon",
    name: "breakdown-riff-a.wav",
    kind: "generation",
    filePath: "D:\\Varynt\\Projects\\iron-halcyon\\generations\\breakdown-riff-a.wav",
    durationSeconds: 18,
    engine: "musicgen",
    model: "small",
    prompt: "half-time breakdown, palm muted guitars, tight kick",
    seed: 331,
    favorite: false,
    createdAt: iso(60 * 6),
    waveformPeaks: peaks(2),
  },
  {
    id: "asset_gen_ih_3",
    songId: "song_iron-halcyon",
    name: "atmos-pad-alt.wav",
    kind: "generation",
    filePath: "D:\\Varynt\\Projects\\iron-halcyon\\generations\\atmos-pad-alt.wav",
    durationSeconds: 45,
    engine: "stable-audio-3-small",
    model: "stable-audio-3-small-music",
    prompt: "atmospheric evolving pad, minor key, dark cinematic underscore",
    seed: 90210,
    favorite: false,
    createdAt: iso(60 * 12),
    waveformPeaks: peaks(3),
  },
  {
    id: "asset_gen_ad_1",
    songId: "song_ashline-drift",
    name: "hook-bed-v1.wav",
    kind: "generation",
    filePath: "D:\\Varynt\\Projects\\ashline-drift\\generations\\hook-bed-v1.wav",
    durationSeconds: 30,
    engine: "stable-audio-3-small",
    model: "stable-audio-3-small-music",
    prompt: "hazy hip-hop bed, distorted guitar accent, half-time",
    seed: 5150,
    favorite: true,
    createdAt: iso(60 * 24),
    waveformPeaks: peaks(4),
  },
  {
    id: "asset_gen_ad_2",
    songId: "song_ashline-drift",
    name: "verse-loop.wav",
    kind: "generation",
    filePath: "D:\\Varynt\\Projects\\ashline-drift\\generations\\verse-loop.wav",
    durationSeconds: 16,
    engine: "musicgen",
    model: "small",
    prompt: "trap-adjacent verse loop, muted guitar",
    seed: 606,
    favorite: false,
    createdAt: iso(60 * 26),
    waveformPeaks: peaks(5),
  },
  {
    id: "asset_gen_ad_3",
    songId: "song_ashline-drift",
    name: "bridge-sketch.wav",
    kind: "generation",
    filePath: "D:\\Varynt\\Projects\\ashline-drift\\generations\\bridge-sketch.wav",
    durationSeconds: 20,
    engine: "musicgen",
    model: "small",
    prompt: "bridge sketch, sparse piano and distant guitar",
    seed: 777,
    favorite: false,
    createdAt: iso(60 * 30),
    waveformPeaks: peaks(6),
  },
  {
    id: "asset_ref_1",
    name: "consented-guide-take.wav",
    kind: "reference",
    filePath: "D:\\Varynt\\References\\consented-guide-take.wav",
    durationSeconds: 14,
    favorite: false,
    createdAt: iso(60 * 24 * 5),
    waveformPeaks: peaks(7),
  },
  {
    id: "asset_vocal_1",
    songId: "song_iron-halcyon",
    name: "guide-verse-1.wav",
    kind: "vocal",
    filePath: "D:\\Varynt\\Projects\\iron-halcyon\\vocals\\guide-verse-1.wav",
    durationSeconds: 24,
    engine: "fish-speech-1.5",
    prompt: "melodic male hook, urgent verse cadence",
    seed: 4242,
    favorite: false,
    createdAt: iso(60 * 8),
    waveformPeaks: peaks(8),
  },
  {
    id: "asset_vocal_2",
    songId: "song_iron-halcyon",
    name: "guide-chorus-1.wav",
    kind: "vocal",
    filePath: "D:\\Varynt\\Projects\\iron-halcyon\\vocals\\guide-chorus-1.wav",
    durationSeconds: 20,
    engine: "fish-speech-1.5",
    prompt: "atmospheric female harmony, sustained chorus lines",
    seed: 4243,
    favorite: true,
    createdAt: iso(60 * 7),
    waveformPeaks: peaks(9),
  },
  {
    id: "asset_stem_v",
    songId: "song_iron-halcyon",
    name: "chorus-wall-v3 — vocals.wav",
    kind: "stem",
    filePath: "D:\\Varynt\\Projects\\iron-halcyon\\stems\\chorus-wall-v3\\vocals.wav",
    durationSeconds: 22,
    favorite: false,
    createdAt: iso(60 * 4),
    waveformPeaks: peaks(10),
  },
  {
    id: "asset_stem_d",
    songId: "song_iron-halcyon",
    name: "chorus-wall-v3 — drums.wav",
    kind: "stem",
    filePath: "D:\\Varynt\\Projects\\iron-halcyon\\stems\\chorus-wall-v3\\drums.wav",
    durationSeconds: 22,
    favorite: false,
    createdAt: iso(60 * 4),
    waveformPeaks: peaks(11),
  },
  {
    id: "asset_stem_b",
    songId: "song_iron-halcyon",
    name: "chorus-wall-v3 — bass.wav",
    kind: "stem",
    filePath: "D:\\Varynt\\Projects\\iron-halcyon\\stems\\chorus-wall-v3\\bass.wav",
    durationSeconds: 22,
    favorite: false,
    createdAt: iso(60 * 4),
    waveformPeaks: peaks(12),
  },
  {
    id: "asset_stem_o",
    songId: "song_iron-halcyon",
    name: "chorus-wall-v3 — other.wav",
    kind: "stem",
    filePath: "D:\\Varynt\\Projects\\iron-halcyon\\stems\\chorus-wall-v3\\other.wav",
    durationSeconds: 22,
    favorite: false,
    createdAt: iso(60 * 4),
    waveformPeaks: peaks(13),
  },
  {
    id: "asset_mix_a",
    songId: "song_iron-halcyon",
    name: "iron-halcyon — mix A.wav",
    kind: "mix",
    filePath: "D:\\Varynt\\Projects\\iron-halcyon\\mixes\\iron-halcyon-mix-A.wav",
    durationSeconds: 218,
    favorite: false,
    createdAt: iso(60 * 3),
    waveformPeaks: peaks(14),
  },
  {
    id: "asset_mix_b",
    songId: "song_iron-halcyon",
    name: "iron-halcyon — mix B.wav",
    kind: "mix",
    filePath: "D:\\Varynt\\Projects\\iron-halcyon\\mixes\\iron-halcyon-mix-B.wav",
    durationSeconds: 219,
    favorite: false,
    createdAt: iso(60 * 2),
    waveformPeaks: peaks(15),
  },
];

export const SEED_JOBS: StudioJob[] = [
  {
    id: "job_active_musicgen",
    type: "music-generation",
    engine: "musicgen",
    device: "cuda",
    songId: "song_iron-halcyon",
    title: "MusicGen — final chorus lift",
    prompt: "final chorus lift, layered guitars, wide stereo synths",
    status: "running",
    progress: 0.42,
    stageLabel: "Rendering",
    outputAssetIds: [],
    createdAt: iso(2),
    startedAt: iso(2),
    logs: [
      "[2026-07-18 14:18:12] Queued.",
      "[2026-07-18 14:18:13] Device: cuda (RTX 5060 Ti).",
      "[2026-07-18 14:18:14] Model loaded: musicgen-small.",
      "[2026-07-18 14:18:15] Sampling tokens 1200/2867...",
    ],
  },
  {
    id: "job_done_stems",
    type: "stem-separation",
    engine: "uvr",
    device: "cuda",
    songId: "song_iron-halcyon",
    title: "UVR — chorus-wall-v3 → 4 stems",
    status: "completed",
    progress: 1,
    stageLabel: "Complete",
    outputAssetIds: ["asset_stem_v", "asset_stem_d", "asset_stem_b", "asset_stem_o"],
    createdAt: iso(60 * 4),
    startedAt: iso(60 * 4),
    completedAt: iso(60 * 4 - 3),
    logs: [
      "[stems] preset: MDX23C — Vocals/Drums/Bass/Other",
      "[stems] separating chorus-wall-v3.wav",
      "[stems] wrote 4 stems (44.1kHz / 24-bit).",
    ],
  },
  {
    id: "job_failed_stable",
    type: "music-generation",
    engine: "stable-audio-3-small",
    device: "cpu",
    songId: "song_ashline-drift",
    title: "Stable Audio — hook alt take",
    prompt: "hazy hip-hop bed, alternate hook variation",
    status: "failed",
    progress: 0.08,
    stageLabel: "Failed",
    outputAssetIds: [],
    createdAt: iso(60 * 1),
    startedAt: iso(60 * 1),
    completedAt: iso(60 * 1 - 1),
    logs: [
      "[hf] resolving model: stabilityai/stable-audio-open-small",
      "[hf] 401 Unauthorized — gated repository.",
    ],
    error: {
      code: "hf_unauthorized",
      message:
        "Stable Audio access is not authorized. Accept the model terms in Hugging Face, then retry.",
      recoverable: true,
    },
  },
];

export const SEED_VOICE_PROFILES: VoiceProfile[] = [
  {
    id: "vp_guide_male_1",
    name: "Guide — Male, warm mid-range",
    referenceAssetId: "asset_ref_1",
    exactTranscript: "This is a consented voice reference used for guide vocals in Varynt Studio.",
    consentConfirmed: true,
    createdAt: iso(60 * 24 * 5),
  },
];

export const SEED_STATUS: ComponentStatus[] = [
  {
    id: "bridge",
    label: "Local bridge",
    state: "installed",
    version: "0.4.2-dev",
    message: "Mock adapter — production bridge not connected.",
    lastCheckedAt: now,
  },
  {
    id: "gpu",
    label: "NVIDIA RTX 5060 Ti",
    state: "available",
    version: "Driver 566.14 · CUDA 12.6",
    device: "cuda",
    message: "16 GB VRAM, 3 GB in use (MusicGen).",
    lastCheckedAt: now,
  },
  {
    id: "musicgen",
    label: "MusicGen (AudioCraft)",
    state: "installed",
    version: "1.3.0",
    device: "cuda",
    message: "Models available: small.",
    lastCheckedAt: now,
  },
  {
    id: "stable-audio",
    label: "Stable Audio 3 Small-Music",
    state: "available",
    version: "small-music",
    device: "cpu",
    message: "Verified CPU route. Medium variant not enabled (requires Flash Attention 2).",
    lastCheckedAt: now,
  },
  {
    id: "fish-speech",
    label: "Fish Speech 1.5",
    state: "installed",
    version: "1.5.0",
    device: "cuda",
    message: "Noncommercial CC BY-NC-SA 4.0. Speech / guide-vocal only.",
    lastCheckedAt: now,
  },
  {
    id: "ffmpeg",
    label: "FFmpeg",
    state: "installed",
    version: "7.0.2",
    message: "On PATH.",
    lastCheckedAt: now,
  },
  {
    id: "uvr",
    label: "Ultimate Vocal Remover",
    state: "unverified",
    message: "Application path not set. Configure in Settings → External app paths.",
    lastCheckedAt: now,
  },
  {
    id: "reaper",
    label: "REAPER",
    state: "unverified",
    message: "Application path not set. Configure in Settings → External app paths.",
    lastCheckedAt: now,
  },
  {
    id: "hf",
    label: "Hugging Face access",
    state: "error",
    message: "One gated model not accepted (Stable Audio Open Small).",
    lastCheckedAt: now,
  },
  {
    id: "storage",
    label: "Workspace storage",
    state: "installed",
    message: "D:\\Varynt — 412 GB free of 2 TB.",
    lastCheckedAt: now,
  },
];

export function makePeaks(seed: number): number[] {
  return peaks(seed);
}
