/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsSongIdRouteImport } from './routes/songs.$songId'
import { Route as SongsSongIdIndexRouteImport } from './routes/songs.$songId.index'

const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/$songId',
  path: '/$songId',
  getParentRoute: () => SongsRoute,
} as any)
const SongsSongIdIndexRoute = SongsSongIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SongsSongIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/songs': typeof SongsRouteWithChildren
  '/songs/$songId': typeof SongsSongIdRouteWithChildren
  '/songs/$songId/': typeof SongsSongIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/songs': typeof SongsRouteWithChildren
  '/songs/$songId': typeof SongsSongIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/songs': typeof SongsRouteWithChildren
  '/songs/$songId': typeof SongsSongIdRouteWithChildren
  '/songs/$songId/': typeof SongsSongIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/songs' | '/songs/$songId' | '/songs/$songId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/songs' | '/songs/$songId'
  id: '__root__' | '/' | '/songs' | '/songs/$songId' | '/songs/$songId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SongsRoute: typeof SongsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof SongsRoute
    }
    '/songs/$songId/': {
      id: '/songs/$songId/'
      path: '/'
      fullPath: '/songs/$songId/'
      preLoaderRoute: typeof SongsSongIdIndexRouteImport
      parentRoute: typeof SongsSongIdRoute
    }
  }
}

interface SongsSongIdRouteChildren {
  SongsSongIdIndexRoute: typeof SongsSongIdIndexRoute
}

const SongsSongIdRouteChildren: SongsSongIdRouteChildren = {
  SongsSongIdIndexRoute: SongsSongIdIndexRoute,
}

const SongsSongIdRouteWithChildren = SongsSongIdRoute._addFileChildren(
  SongsSongIdRouteChildren,
)

interface SongsRouteChildren {
  SongsSongIdRoute: typeof SongsSongIdRouteWithChildren
}

const SongsRouteChildren: SongsRouteChildren = {
  SongsSongIdRoute: SongsSongIdRouteWithChildren,
}

const SongsRouteWithChildren = SongsRoute._addFileChildren(SongsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SongsRoute: SongsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
